name        : plex-media-player
version     : 2.4.1
release     : 1
source      :
    - https://github.com/plexinc/plex-media-player/archive/v2.4.1.787-54a020cd.tar.gz : 827f26c09eb74ae46ad51bab8f8c44c68b3409dc8657bb10f1ff949835201a75
    - https://artifacts.plex.tv/web-client-pmp/40-2e815e113d1fc7/buildid.cmake : 9d04c91cd3a9f91a4f1417298cbc0b061670cfa7bb069b5ea2cc747545426f00
    - https://artifacts.plex.tv/web-client-pmp/40-2e815e113d1fc7/web-client-desktop-3.35.2-13d1fc7.tar.xz : 9886be9df9d0428ed7be72a4c47b3d783a90cf3fd3e4b7645838641e48f12087
    - https://artifacts.plex.tv/web-client-pmp/40-2e815e113d1fc7/web-client-desktop-3.35.2-13d1fc7.tar.xz.sha1 : 5d6040801c9636bd28960ac43065b8711dfd0dc57f650b5f547b929c1ccf7d70
    - https://artifacts.plex.tv/web-client-pmp/40-2e815e113d1fc7/web-client-tv-3.36.2-2e815e1.tar.xz : af723f9569527cf76be324bea2c34f5dcc4e0a95c6f22352498199f847ee505d
    - https://artifacts.plex.tv/web-client-pmp/40-2e815e113d1fc7/web-client-tv-3.36.2-2e815e1.tar.xz.sha1 : 81c0494ebcc4a349d2a6cf926364cc39267c0c05cd1fd8393843f8c859b54149
license     : GPL-2.0
component   : multimedia.video
summary     : Plex Media Player is the go-to app for Home Theater PCs (HTPCs) connected to big screen TVs.
description : |
    Plex Media Player is the go-to app for Home Theater PCs (HTPCs) connected to big screen TVs.
builddeps   :
    - pkgconfig(gl)
    - pkgconfig(libcec)
    - pkgconfig(mpv)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebChannel)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sdl2)
rundeps     :
    - qt5-quickcontrols
setup       : |
    sed -i 's|include(GetGitRevisionDescription)||' CMakeModules/VersionConfiguration.cmake
    sed -i 's|get_git_head_revision(REFSPEC FULL_GIT_REVISION)||' CMakeModules/VersionConfiguration.cmake
    mkdir -p "$workdir/build/dependencies"
    cd "$workdir/build/dependencies"
    ln -sf "$sources/buildid.cmake" buildid-40-2e815e113d1fc7.cmake
    ln -sf "$sources/web-client-desktop-3.35.2-13d1fc7.tar.xz" .
    ln -sf "$sources/web-client-desktop-3.35.2-13d1fc7.tar.xz.sha1" .
    ln -sf "$sources/web-client-tv-3.36.2-2e815e1.tar.xz" .
    ln -sf "$sources/web-client-tv-3.36.2-2e815e1.tar.xz.sha1" .
build       : |
    cd "$workdir/build"
    %cmake -DCMAKE_SKIP_RPATH=1 \
           -DFULL_GIT_REVISION="54a020cd" \
           -DQTROOT=/usr/share/qt5/ \
           ..
    make
install     : |
    cd "$workdir/build"
    %make_install
    install -Dm644 "$pkgfiles/plex-media-player.desktop" "$installdir/usr/share/applications/plex-media-player.desktop"
    install -Dm644 "$workdir/resources/images/icon.png" "$installdir/usr/share/icons/hicolor/256x256/apps/plex-media-player.png"
